version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Repo Sync with Custom Flags
          command: repo sync -c --force-sync --no-tags --no-clone-bundle --optimized-fetch --prune -j2 --fail-fast
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
