version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Repo Sync with Optimized Flags
          command: repo sync --optimized-fetch --prune -j2
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
